### ISSUE TITLE
Feature query na pseudo-classe `:has()`

### ISSUE THREAD

**Issue by ddeltree** [ddeltree/cpt#3]
Essa pseudo-classe é usada pra diminuir a margem esquerda do conteúdo quando a [sidebar](https://github.com/ddeltree/cpt/blob/main/src/components/Sidebar.astro) colapsa, mas essa pseudo-classe não possui suporte no Firefox ESR.

```css
#sidebar:has(> #sidebar-toggle:checked) + #rightside-content {
  --sidebar-width: var(--collapsed-width);
}
```

Seria bom se a sidebar não pudesse colapsar nesses casos sem suporte.
