### ISSUE TITLE
dark mode 

### ISSUE THREAD

**Issue by ddeltree** [ddeltree/cpt#4]
```css
body {
  background-color: white;
  color: black;
}

@media (prefers-color-scheme: dark) {
  body {
    background-color: black;
    color: white;
  }
}
```
